import "@/public/css/vendor/bootstrap.min.css"
import "@/public/css/vendor/font-awesome.css"
import "@/public/css/vendor/flaticon/flaticon.css"
import "@/public/css/vendor/slick.css"
import "@/public/css/vendor/slick-theme.css"
import "@/public/css/vendor/magnific-popup.css"
import "@/public/css/vendor/base.css"
import "@/public/css/style.min.css"

import Header from "@/component/Header/Header"
import Footer from "@/component/Footer/Footer"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html className="no-js" lang="en">
            <body className="sticky-header newsletter-popup-modal">
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
